live_config_reload = true

[[colors.indexed_colors]]
color = "0xf5871f"
index = 16

[[colors.indexed_colors]]
color = "0xa3685a"
index = 17

[[colors.indexed_colors]]
color = "0xe0e0e0"
index = 18

[[colors.indexed_colors]]
color = "0xd6d6d6"
index = 19

[[colors.indexed_colors]]
color = "0x969896"
index = 20

[[colors.indexed_colors]]
color = "0x282a2e"
index = 21

[colors.bright]
black = "0x8e908c"
blue = "0x4271ae"
cyan = "0x3e999f"
green = "0x718c00"
magenta = "0x8959a8"
red = "0xc82829"
white = "0x1d1f21"
yellow = "0xeab700"

[colors.cursor]
cursor = "0x4d4d4c"
text = "0xffffff"

[colors.normal]
black = "0xffffff"
blue = "0x4271ae"
cyan = "0x3e999f"
green = "0x718c00"
magenta = "0x8959a8"
red = "0xc82829"
white = "0x4d4d4c"
yellow = "0xeab700"

[colors.primary]
background = "0xffffff"
foreground = "0x4d4d4c"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1
