window:
  padding:
    x: 16
    y: 16
  decorations: none
  opacity: 1.0
  dynamic_title: false
scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 100000

  # Scrolling distance multiplier.
  multiplier: 3

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 13.0
  offset:
    x: 1
    y: 1

  #glyph_offset:
  #  x: 0
  #  y: 0
  use_thin_strokes: false

#draw_bold_text_with_bright_colors: false

schemes:

    # Default colors
  solarized-dark: &solarized-dark
    primary:
      background: '0x002b36'
      foreground: '0x839496'

    # Normal colors
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'

    # Bright colors
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'
  tokyo-night: &tokyo-night # Default colors
    primary:
      background: "0x1a1b26"
      foreground: "0xa9b1d6"

    # Normal colors
    normal:
      black: "0x32344a"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xad8ee6"
      cyan: "0x449dab"
      white: "0x787c99"

    # Bright colors
    bright:
      black: "0x444b6a"
      red: "0xff7a93"
      green: "0xb9f27c"
      yellow: "0xff9e64"
      blue: "0x7da6ff"
      magenta: "0xbb9af7"
      cyan: "0x0db9d7"
      white: "0xacb0d0"

  tokyo-night-storm: &tokyo-night-storm # Default colors
    primary:
      background: "0x24283b"
      foreground: "0xa9b1d6"

    # Normal colors
    normal:
      black: "#32344a"
      red: "#f7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xad8ee6"
      cyan: "0x449dab"
      white: "0x9699a8"

    # Bright colors
    bright:
      black: "0x444b6a"
      red: "0xff7a93"
      green: "0xb9f27c"
      yellow: "0xff9e64"
      blue: "0x7da6ff"
      magenta: "0xbb9af7"
      cyan: "0x0db9d7"
      white: "0xacb0d0"
  onedark: &onedark
    primary:
      background: "0x1e2127"
      foreground: "0xabb2bf"

    # Normal colors
    normal:
      black: "0x1e2127"
      red: "0xe06c75"
      green: "0x98c379"
      yellow: "0xd19a66"
      blue: "0x61afef"
      magenta: "0xc678dd"
      cyan: "0x56b6c2"
      white: "0xabb2bf"

    # Bright colors
    bright:
      black: "0x5c6370"
      red: "0xe06c75"
      green: "0x98c379"
      yellow: "0xd19a66"
      blue: "0x61afef"
      magenta: "0xc678dd"
      cyan: "0x56b6c2"
      white: "0xffffff"
  dracunized-knight: &dracunized-knight # Default colors
    primary:
      background: "#101a27"
      foreground: "#c5c3ce"

    # Normal colors
    normal:
      black: "#313a33"
      red: "#c71952"
      green: "#55a967"
      yellow: "#e0cf77"
      blue: "#5164df"
      magenta: "#b300df"
      cyan: "#00a8af"
      white: "#ccccdd"

    # Bright colors
    bright:
      black: "#424b44"
      red: "#d82a63"
      green: "#66bf78"
      yellow: "#f1d088"
      blue: "#6275f0"
      magenta: "#c411f0"
      cyan: "#11b9c0"
      white: "#ddddee"
colors: *solarized-dark

selection:
  #semantic_escape_chars: ",?`|:\"' ()[]{}<>\t"

  save_to_clipboard: true

#cursor:
# Cursor style
#style:
# Cursor shape
#
# Values for `shape`:
#   - ? Block
#   - _ Underline
#   - | Beam
#shape: Block

# Cursor blinking state
#
# Values for `blinking`:
#   - Never: Prevent the cursor from ever blinking
#   - Off: Disable blinking by default
#   - On: Enable blinking by default
#   - Always: Force the cursor to always blink
#blinking: Off

# Vi mode cursor style
#
# If the vi mode cursor style is `None` or not specified, it will fall back to
# the style of the active value of the normal cursor.
#
# See `cursor.style` for available options.
#vi_mode_style: None

# Cursor blinking interval in milliseconds.
#blink_interval: 750

# If this is `true`, the cursor will be rendered as a hollow box when the
# window is not focused.
#unfocused_hollow: true

# Thickness of the cursor relative to the cell width as floating point number
# from `0.0` to `1.0`.
#thickness: 0.15

# Live config reload (changes require restart)
live_config_reload: true
# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g.
# `/bin/fish`. Entries in `shell.args` are passed unmodified as arguments to the
# shell.
#
# Default:
#   - (macOS) /bin/bash --login
#   - (Linux/BSD) user login shell
#   - (Windows) powershell
#shell:
#  program: /bin/bash
#  args:
#    - --login

# Startup directory
#
# Directory the shell is started in. If this is unset, or `None`, the working
# directory of the parent process will be used.
#working_directory: None

# Send ESC (\x1b) before characters when alt is pressed.
#alt_send_esc: true