#!/usr/bin/env sh

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config window_placement             first_child

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_topmost               off
yabai -m config window_shadow                off

# Window Opacity
yabai -m config window_opacity               on

# yabai -m config active_window_border_color   0x0002b36
# yabai -m config normal_window_border_color   0x0DDE2E4

yabai -m config window_border off

yabai -m config split_ratio                  0.50

yabai -m config auto_balance                 off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   10

yabai -m config --space 7 layout float
yabai -m config --space 8 layout float
yabai -m config --space 9 layout float
yabai -m config --space 10 layout float

yabai -m space 1 --label Code
yabai -m space 2 --label Web
yabai -m space 3 --label Notes
yabai -m space 4 --label Chat
yabai -m space 5 --label Mail
yabai -m space 6 --label Music
yabai -m space 7 --label Extra.1
yabai -m space 8 --label Extra.2
yabai -m space 9 --label Extra.3


# Development
yabai -m rule --add app="iterm2" space=1
yabai -m rule --add app="Code" space=1

# Notes
yabai -m rule --add app="Notion" space=3

# Browsers
yabai -m rule --add app="Chrome" space=2
yabai -m rule --add app="Safari" space=2

# Chat & Video
yabai -m rule --add app="zoom.us" space=4
yabai -m rule --add app="Slack" space=4
yabai -m rule --add app="Messages" space=4
yabai -m rule --add app="FaceTime" space=4


# Mail
yabai -m rule --add app="Spark" space=5

# Music
yabai -m rule --add app="Spotify" space=6
yabai -m rule --add app="Music" space=6

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off

yabai -m config external_bar all:27:0

