#!/usr/bin/env sh

# Load SA for Yabai
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Aliases
alias ym='yabai -m'
alias cfg='ym config'
alias rule='ym rule'
alias sig='ym signal'

# CONFIG
# ----------------------------------
# Default Configuration
# -- can be bsp, stakc, or float
cfg layout bsp 

# Window Management
cfg window_placement second_child
# Turns off default shadow of window, increases load time
cfg window_shadow off 
cfg window_opacity on
cfg split_ratio 0.50
cfg auto_balance off

# Padding
cfg top_padding 3
cfg bottom_padding 3
cfg left_padding 3
cfg right_padding 3
cfg window_gap 2

# Mouse settings
cfg mouse_follows_focus on
cfg mouse_modifier alt
# -- left click + drag
cfg mouse_action1 move
# -- right click + drag
cfg mouse_action2 resize
# -- drag and drop the window will swap positions
ym mouse_drop_action swap

# Border Colors
cfg window_border on
cfg window_border_width 1
cfg active_window_border_color 0x9994e2d5
cfg normal_window_border_color 0x119bff4a

# Spaces
# ----------------------------------
# Space Labels
ym space 1 --label Home
ym space 2 --label Browser
ym space 3 --label Code
ym space 4 --label Terminal
ym space 5 --label Chat
ym space 6 --label Music

# Floating Spaces
# float the Home Space
cfg --space 1 layout float
cfg --space 7 layout float
cfg --space 8 layout float
cfg --space 9 layout float

# RULES
# ----------------------------------
# Exclusion
rule --add app="System Settings$"  manage=off
rule --add app="App Store"  manage=off
rule --add app="Shottr" manage=off
rule --add app="^Finder$" manage=off
rule --add app="RayCast" manage=off

# Designations
# space=2
rule --add app="Firefox" space=2
rule --add app="Chrome" space=2
rule --add app="Safari" space=2
# space=3
rule --add app="Code" space=3
rule --add app="WezTerm" space=4
# space=4
rule --add app="Notion" space=4
rule --add app="Craft" space=4
# space=5
rule --add app="Slack" space=5
rule --add app="zoom.us" space=5
# space=6
rule --add app="Music" space=6
rule --add app="Spotify" space=6

# SIGNALS
# ----------------------------------
# script disables any border on floating spaces 1,7,8,9
sig --add event=application_launched action="$HOME/.bin/yb_noborder_on_float.sh"
sig --add event=space_changed action="$HOME/.bin/yb_noborder_on_float.sh"
sig --add event=window_created action="$HOME/.bin/yb_noborder_on_float.sh"


# -- OLD CONFIG --
# ----------------------------------
# sudo yabai --load-sa
# ym signal --add event=dock_did_restart action="sudo yabai --load-sa"

