#!/usr/bin/env sh

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             first_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff7aa2f7
yabai -m config normal_window_border_color   0xffcfc9c2
yabai -m config insert_feedback_color        0xff61afef
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               10
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8
yabai -m config --space 8 layout float
yabai -m config --space 9 layout float
yabai -m config --space 10 layout float

yabai -m space 1 --label Code
yabai -m space 2 --label Web
yabai -m space 3 --label Notes
yabai -m space 4 --label Chat
yabai -m space 5 --label Mail
yabai -m space 6 --label Music
yabai -m space 7 --label Extra.1
yabai -m space 8 --label Extra.2
yabai -m space 9 --label Extra.3
yabai -m space 10 --label Extra.4

yabai -m rule --add app="Chrome" space=2
yabai -m rule --add app="Safari" space=2
yabai -m rule --add app="zoom.us" space=4
yabai -m rule --add app="Discord"       space=5

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off

yabai -m config external_bar all:27:0

