#!/bin/bash
# --------------------------------------------------------- #
# Config
# --------------------------------------------------------- #
config_dir="$HOME/.config/sketchybar"

# Bar
bar_height=28
bar_padding=3
bar_y_offset=2
bar_margin=2
bar_corner_radius=3
bar_color="0x551e1e2e"
bar_border_color="0x3394e2d5"

# Font
font_face="JetBrainsMono Nerd Font"

# icons
icon_color="0xff24273a"
icon_font="$font_face:Medium:20.0" 
icon_padding=5



# colors
label_color="0xffcad3f5"
popup_background_color="0xff1e1e2e"
popup_border_color="0xffcad3f5"

# --------------------------------------------------------- #

# Default Configurations
source $config_dir/config/defaults.sh
# --------------------------------------------------------- #
# Items Added
# --------------------------------------------------------- #
# Space Icon [ config: config/space_icon.sh , script: scripts/space_icon.sh]
source $config_dir/config/space_icon.sh
# Space Label [ config: config/space_label.sh, script: scripts/space_label.sh]
# source $config_dir/config/space_label.sh
# Window Label
source $config_dir/config/window_label.sh
